window.globalAppTranslations = window.globalAppTranslations || {
  th: {
    // Navigation & App Shell
    home: "หน้าหลัก",
    leaveCheck: "ตรวจใบลา",
    employeeManagement: "ระบบจัดการส่วนกลาง",
    employees: "พนักงาน",
    userView: "หน้าพนักงาน",
    holidays: "วันหยุด",
    cardSystem: "บัตรพนักงาน",
    news: "ข่าวสาร",
    settings: "ตั้งค่า",
    logout: "ออกจากระบบ",
    logoutShort: "ออก",
    back: "ย้อนกลับ",
    backShort: "กลับ",
    save: "บันทึก",
    cancel: "ยกเลิก",
    confirm: "ยืนยัน",
    close: "ปิด",
    delete: "ลบ",
    edit: "แก้ไข",
    refresh: "รีเฟรชข้อมูลล่าสุด",
    loading: "กำลังโหลดข้อมูล...",
    all: "ทั้งหมด",
    
    // Notifications
    notifications: "การแจ้งเตือน",
    markAllRead: "อ่านทั้งหมด",
    unreadSuffix: "รายการใหม่",
    viewAllNotif: "ดูการแจ้งเตือนทั้งหมด",
    loadingNotif: "กำลังโหลดแจ้งเตือน...",
    
    // User Home Dashboard
    hello: "สวัสดีค่ะ",
    approverModeTitle: "ระบบหัวหน้างาน / HR",
    approverModeSub: "สลับไปหน้าอนุมัติใบลาและจัดการข้อมูล ➜",
    heroLeaveTitle: "ยื่นใบลาออนไลน์",
    heroLeaveSub: "กรอกฟอร์มขออนุญาตลา อนุมัติตามลำดับขั้นไว",
    leaveBalanceTitle: "สิทธิ์วันลาคงเหลือ",
    quickMenuTitle: "เลือกเมนูการใช้งาน",
    ruleTitle: "หลักเกณฑ์การลา",
    ruleSub: "เปิดอ่านเงื่อนไขบริษัท",
    historyTitle: "ประวัติการลา",
    historySub: "ตรวจสอบสถานะใบลา",
    profileTitle: "ข้อมูลพนักงาน",
    profileSub: "ตรวจสอบรหัส ชื่อ และวันเริ่มงาน",
    holidayTitle: "ปฏิทินวันหยุด",
    holidaySub: "วันหยุดประจำปีบริษัท",
    cardTitle: "บัตรพนักงานดิจิทัล",
    cardSub: "แสดง QR Code ประจำตัว",
    guideTitle: "คู่มือการใช้งาน",
    guideSub: "วิธีใช้งานระบบลาออนไลน์",
    lineConnect: "เชื่อมต่อ LINE",
    lineNotif: "รับแจ้งเตือนผ่านมือถือ",
    viewCard: "ดูบัตรพนักงาน",
    recentListHeading: "รายการล่าสุด",
    viewAll: "ดูทั้งหมด",
    loadingLeave: "กำลังโหลดรายการลา...",
    teamTitle: "สมาชิกพนักงานในแผนก",
    teamSub: "เพื่อนร่วมงานในแผนกของคุณ",
    
    // Leave Form (leave-user.html)
    leaveFormTitle: "ใบลาออนไลน์",
    companySubtitle: "บริษัท พี.วี.ที. แอนด์ ที.พลาส จำกัด · ปี 2569",
    periodSubtitle: "วันที่ 1 ธันวาคม – 30 พฤศจิกายน",
    ruleBtnText: "📘 หลักเกณฑ์",
    applicantInfoTitle: "ข้อมูลผู้ขออนุมัติลา",
    autofillBadge: "ระบบดึงข้อมูลอัตโนมัติ",
    empCodeLabel: "รหัสพนักงาน",
    empNameLabel: "ชื่อ-นามสกุล พนักงาน",
    empPosLabel: "ตำแหน่ง",
    empDeptLabel: "แผนก / ฝ่าย",
    empStartLabel: "วันเริ่มงาน",
    leaveBalanceLabel: "สิทธิคงเหลือ",
    leaveBalanceSelectFirst: "กรุณาเลือกประเภทการลาก่อน",
    socialSecurityLabel: "สิทธิประกันสังคม",
    socialSecurityNote: "(เปลี่ยนสิทธิกรุณาแจ้ง HR)",
    lineAlertNotice: "แจ้งเตือนผ่าน LINE: ระบบจะส่งแจ้งเตือนสถานะใบลานี้ไปยัง LINE ของท่านและหัวหน้างานทันทีที่กดส่งคำขอ และเมื่อได้รับการอนุมัติ/ปฏิเสธ",
    checkBeforeSaveNotice: "ตรวจสอบก่อนบันทึก: ลาพักผ่อนล่วงหน้าอย่างน้อย 3 วัน · ลากิจแจ้งล่วงหน้า 1 วัน · ลาป่วยแจ้งภายใน 4 ชั่วโมงแรก พร้อมใบรับรองแพทย์",
    leaveCardContainerTitle: "ใบขออนุญาติลา",
    btnAddLeaveItem: "＋ เพิ่มรายการลา",
    btnSaveLeave: "💾 บันทึกคำขอลา",
    sec1Divider: "หมวดหมู่ที่ 1: วันที่และกรอบเวลาการลา",
    sec2Divider: "หมวดหมู่ที่ 2: รายละเอียดประเภทการลาและหลักฐาน",
    sec3Divider: "หมวดหมู่ที่ 3: จำนวนเวลาและชั่วโมงที่ขอลา",
    sec4Divider: "หมวดหมู่ที่ 4: สถานะผลการพิจารณาและอนุมัติ",
    writeDateLabel: "วันที่เขียนคำขอ",
    startDateLabel: "เริ่มวันที่ลา",
    endDateLabel: "สิ้นสุดวันที่ลา",
    leaveTypeLabel: "ประเภทการลา",
    leaveTypePlaceholder: "-- เลือกประเภทการลา --",
    reasonLabel: "สาเหตุ / เหตุผลการลา",
    reasonPlaceholder: "ระบุเหตุผลความจำเป็น...",
    attachProofLabel: "แนบหลักฐานรูปภาพ",
    selectProofBtn: "📁 เลือกรูปภาพหลักฐาน",
    hoursMorningLabel: "จำนวนชั่วโมงเช้า (0-4)",
    hoursAfternoonLabel: "จำนวนชั่วโมงบ่าย (0-4)",
    totalDurationLabel: "สรุปรวมระยะเวลาที่ขอลา",
    deptHeadLabel: "หัวหน้าแผนก",
    deptManagerLabel: "ผู้จัดการฝ่าย",
    hrDeptLabel: "ฝ่ายบุคคล",
    btnRemoveItem: "ลบรายการนี้",
    formGuideTitle: "วิธีกรอกแบบฟอร์มใบลา",
    formGuideFab: "แนะนำการกรอกฟอร์ม",
    
    // Leave History (leave-history.html)
    historyPageTitle: "ประวัติการลาของฉัน",
    statAll: "ทั้งหมด",
    statPending: "รออนุมัติ",
    statApproved: "อนุมัติแล้ว",
    statCancelReq: "รอ HR ยกเลิก",
    statTotalDays: "วันลารวมที่ใช้",
    filterTitle: "กรองรายการ:",
    chipAll: "ทั้งหมด",
    chipPending: "รออนุมัติ",
    chipApproved: "อนุมัติแล้ว",
    chipCancelReq: "🔄 รอ HR ยกเลิก",
    chipRejectedCancelled: "❌ ไม่อนุมัติ / ยกเลิกแล้ว",
    thLeaveType: "ประเภทการลา",
    thDateRange: "ช่วงวันที่",
    thDays: "จำนวนวัน",
    thReason: "เหตุผลการลา",
    thStatus: "สถานะ",
    thAction: "จัดการคำขอ",
    btnDirectCancel: "ยกเลิกคำขอ",
    btnRequestCancel: "ขอยกเลิกใบลา",
    badgeWaitingHr: "ส่งเรื่องแล้ว",
    reasonCancelPrefix: "เหตุผลที่ยกเลิก:",
    reasonRejectPrefix: "เหตุผลที่ไม่อนุมัติ:",
    emptyHistory: "ไม่พบรายการใบลาตามเงื่อนไขที่เลือก",
    emptyHistoryLogin: "กรุณาเข้าสู่ระบบเพื่อดูประวัติการลา",
    
    // Profile Page (profile-user.html)
    profilePageTitle: "ข้อมูลพนักงาน",
    profilePageSub: "ตรวจสอบข้อมูลโปรไฟล์และการแจ้งเตือน LINE",
    profileDetailsHeading: "รายละเอียดโปรไฟล์",
    lblFullName: "ชื่อ-นามสกุล",
    lblEmpCode: "รหัสพนักงาน",
    lblDept: "ฝ่าย / แผนก",
    lblPos: "ตำแหน่งงาน",
    lblEmail: "อีเมล / บัญชี",
    lblRole: "สิทธิ์การใช้งาน",
    lblStartDate: "วันเริ่มงาน",
    lineSectionHeading: "การแจ้งเตือนใบลานี้ผ่าน LINE (LINE Notification)",
    lineAutoLinkTitle: "ผูกบัญชี LINE อัตโนมัติ (แนะนำ)",
    lineAutoLinkSub: "รับรหัสเชื่อมต่อและส่งไปที่ LINE OA เพื่อผูกบัญชีทันทีโดยไม่ต้องหา User ID เอง",
    btnGetLineCode: "ขอรหัสเชื่อมต่อ LINE",
    lineManualTitle: "หรือระบุ LINE User ID ด้วยตนเอง",
    btnSaveLine: "💾 บันทึก",
    
    // Holidays (holidays.html)
    holidayPageTitle: "ปฏิทินวันหยุดประจำปี",
    holidayPageSub: "PVT HR HOLIDAY MANAGEMENT SYSTEM",
    tabCompanyHolidays: "วันหยุดบริษัท",
    tabTeamLeaves: "วันลาของคนในแผนก",
    statTotalHolidays: "วันหยุดรวมทั้งหมด (ปีนี้)",
    statNextHoliday: "วันหยุดถัดไป",
    statRemainingHolidays: "วันหยุดคงเหลือปีนี้",
    heroNextHolidayTitle: "วันหยุดถัดไปที่กำลังจะถึง",
    heroDaysAhead: "วันข้างหน้า",
    heroNoUpcoming: "ไม่มีวันหยุดถัดไปในปีนี้",
    heroNoUpcomingDesc: "ผ่านพ้นวันหยุดทั้งหมดของปีนี้เรียบร้อยแล้ว",
    searchHolidayPlaceholder: "ค้นหาชื่อวันหยุด หรือวันที่...",
    btnAddHoliday: "เพิ่มวันหยุดใหม่",
    typeOfficial: "วันหยุดนักขัตฤกษ์",
    typeCompany: "วันหยุดประจำปีบริษัท",
    typeSubstitution: "วันหยุดชดเชย",
    optAllYear: "📅 แสดงทั้งปี (สรุปรายปี)",
    optAllCategories: "ทุกประเภทวันหยุด",
    optOfficial: "วันหยุดนักขัตฤกษ์ / ตามประเพณี",
    optCompany: "วันหยุดพิเศษบริษัท",
    optSubstitution: "วันหยุดชดเชย",
    calMonthlyTitle: "ปฏิทินวันหยุด (แบบรายเดือน)",
    teamCalTitle: "ปฏิทินวันลาของทีม",
    companySummaryMonth: "สรุปวันหยุดเดือนนี้",
    teamSummaryTitle: "สรุปรายชื่อผู้ลา",
    searchTeamPlaceholder: "ค้นหาชื่อ...",
    thNo: "ลำดับ",
    thDate: "วันที่หยุด",
    thDayOfWeek: "วันในสัปดาห์",
    thHolidayName: "ชื่อวันหยุด",
    thCategory: "ประเภทวันหยุด",
    thCountdown: "นับถอยหลัง",
    thDesc: "หมายเหตุ / รายละเอียด",
    thManage: "จัดการ",
    modalAddTitle: "เพิ่มวันหยุดใหม่",
    modalEditTitle: "แก้ไขข้อมูลวันหยุด",
    modalBtnSave: "บันทึกวันหยุด",
    
    // Leave Rules (leave-rules.html)
    rulesPageTitle: "หลักเกณฑ์และเงื่อนไขการลา",
    rulesPageSub: "สิทธิประโยชน์และข้อกำหนดทางวินัยพนักงาน PVT",
    
    // Guide Page (full-guide.html)
    guidePageTitle: "คู่มือการใช้งานระบบพนักงาน (ฉบับสมบูรณ์)",
    guideTopicHeading: "หัวข้อแนะนำ",
    
    // Units & Types
    unitDays: "วัน",
    unitHours: "ชม.",
    unitMinutes: "นาที",
    leaveSick: "ลาป่วย",
    leaveAnnual: "วันหยุดพักผ่อนประจำปี",
    leaveBusiness: "ลากิจ",
    leaveSterilization: "การลาเพื่อทำหมัน",
    leaveMilitary: "การลาเพื่อรับราชการทหาร",
    leaveOrdination: "การลาเพื่ออุปสมบท",
    leaveFuneral: "การลาเพื่อฌาปนกิจศพ",
    leaveOther: "ลาอื่น ๆ",
    leaveMaternity: "การลาเพื่อคลอดบุตร",
    
    // Statuses
    statusApproved: "อนุมัติแล้ว",
    statusPending: "รออนุมัติ",
    statusRejected: "ไม่อนุมัติ",
    statusCancelReq: "รอ HR อนุมัติยกเลิก",
    statusCancelled: "ยกเลิกแล้ว",
    statusWaitingReview: "รอพิจารณา"
  },
  lo: {
    // Navigation & App Shell
    home: "ໜ້າຫຼັກ",
    leaveCheck: "ກວດສອບໃບລາ",
    employeeManagement: "ລະບົບຈັດການສ່ວນກາງ",
    employees: "ພະນັກງານ",
    userView: "ໜ້າພະນັກງານ",
    holidays: "ວັນພັກ",
    cardSystem: "ບັດພະນັກງານ",
    news: "ຂ່າວສານ",
    settings: "ຕັ້ງຄ່າ",
    logout: "ອອກຈາກລະບົບ",
    logoutShort: "ອອກ",
    back: "ກັບຄືນ",
    backShort: "ກັບ",
    save: "ບັນທຶກ",
    cancel: "ຍົກເລີກ",
    confirm: "ຢືນຢັນ",
    close: "ປິດ",
    delete: "ລຶບ",
    edit: "ແກ້ໄຂ",
    refresh: "ໂຫຼດຂໍ້ມູນໃໝ່",
    loading: "ກຳລັງໂຫຼດຂໍ້ມູນ...",
    all: "ທັງໝົດ",
    
    // Notifications
    notifications: "ການແຈ້ງເຕືອນ",
